// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awypstfmguibmmhthrrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3eXBzdGZtZ3VpYm1taHRocnJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODAzMTIsImV4cCI6MjA2NDQ1NjMxMn0.zmgDx_etBEkg6KoOgY5MzOdyA6I1aYkGxsvfClTDRt0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);